// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FfxX6ilAy9bNEG6nXS0Sa7wlue4ihjg',
    appId: '1:307780216159:web:bd4e44a5598a2c496e02ea',
    messagingSenderId: '307780216159',
    projectId: 'crypto-wallet-2ecbe',
    authDomain: 'crypto-wallet-2ecbe.firebaseapp.com',
    storageBucket: 'crypto-wallet-2ecbe.appspot.com',
    measurementId: 'G-XKMJ4BEJQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ5Efmx61YdYJ7vUzEZcbUg0PBdABbI4c',
    appId: '1:307780216159:android:6665a5d5a255b13f6e02ea',
    messagingSenderId: '307780216159',
    projectId: 'crypto-wallet-2ecbe',
    storageBucket: 'crypto-wallet-2ecbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTf5KkHkiGRbtY1E7z75pptmwLGbF0Xs0',
    appId: '1:307780216159:ios:eaefd08f86e190916e02ea',
    messagingSenderId: '307780216159',
    projectId: 'crypto-wallet-2ecbe',
    storageBucket: 'crypto-wallet-2ecbe.appspot.com',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTf5KkHkiGRbtY1E7z75pptmwLGbF0Xs0',
    appId: '1:307780216159:ios:c6cfa10df3995d2e6e02ea',
    messagingSenderId: '307780216159',
    projectId: 'crypto-wallet-2ecbe',
    storageBucket: 'crypto-wallet-2ecbe.appspot.com',
    iosBundleId: 'com.example.cryptoWallet.RunnerTests',
  );
}
